### ISSUE TITLE
Cache toggles between app launches

### ISSUE THREAD

**Issue by kdawgwilk** [launchdarkly/android-client#19]
We expected LaunchDarkly to cache the toggles and their rules across app launches so that way when someone opens the app when they have no internet they get the same toggles that they got previously when they did have a connection.

**Comment by drichelson** [comment]
Hi @kdawgwilk, Thanks for reaching out. This is already implemented in the Android client. If you're not seeing what you expect please email us: support@launchdarkly.com

**Comment by kdawgwilk** [comment]
@simon-the-canadian You might be able to explain better what is happening

**Comment by simon-the-canadian** [comment]
So by looking at the logs it looks like the sdk fails to create the shared preferences file:

Couldn't create directory for SharedPreferences file /data/user/0/com.busyllc.busybusy/shared_prefs/LaunchDarkly-com.busyllc.busybusy

**Comment by simon-the-canadian** [comment]
![screen shot 2017-03-15 at 9 48 00 am](https://cloud.githubusercontent.com/assets/17653830/23957539/3d98e736-0965-11e7-960b-829432fce636.png)

If you look at the map in shared preferences there are 22 toggles.

![screen shot 2017-03-15 at 9 52 03 am](https://cloud.githubusercontent.com/assets/17653830/23957552/4ac99018-0965-11e7-98df-c7c97f7f2a3b.png)

After killing the app and launching it again in airplane mode the toggles are gone.

**Comment by simon-the-canadian** [comment]
@drichelson Is there a special configuration of the darkly client required for toggles to persist? I'm using the all flags method on the client rather than the boolean variation method. Could that affect anything?
