### ISSUE TITLE
Upadate to latest version of OKHttp

### ISSUE THREAD

**Issue by ian-ellis** [launchdarkly/android-client#20]
I have been struggling to integrate your SDK with our app but finally got the bottom of the problem. It appears you have a dependency on OKhttp 3.4.1, while other components in our application use 3.6.0. Gradle chooses the higher versions in this instance, which led to OKHttp to hang when initializing the SDK asynchronously.

I have managed to patch the issue using the following code

`configurations.all {
  //launch darkly requires this version
  resolutionStrategy.force 'com.squareup.okhttp3:okhttp:3.4.1'
}`

However, I am unsure of any knock-on effects of such a hack.

I can see that the latest version of your okhttp-eventsource library (1.1.0) uses the latest okhttp (3.6.0), so would assume that upgrading the android-client version should not be too difficult

**Comment by drichelson** [comment]
Addressed in release [2.0.0](https://github.com/launchdarkly/android-client/releases/tag/2.0.0)
