### ISSUE TITLE
Version 2.3.0 still produces logs in production

### ISSUE THREAD

**Issue by byencho** [launchdarkly/android-client#38]
While there have been some changes recently to use `Timber` for logging, there are still places that use `Log.d`, `Log.e`, etc. for logging and these logs show up in release builds of apps including LD. This is true in particular of the `HttpFeatureFlagFetcher` class (logged as `LDFeatureFlagFetcher`). Ideally all remaining logging in the app would be configurable (by, for example, switching to use `Timber` or `Logger`).

**Comment by arun251** [comment]
Hi @byencho we replaced all the other `Log` usages with `Timber`. This is fixed in version 2.3.1.
