### ISSUE TITLE
Timber update 4.6.0 --> 4.7.0

### ISSUE THREAD

**Issue by brian98point6** [launchdarkly/android-client#42]
Hi,
We don't use Timber in our app but pulling in LaunchDarkly's client pulls in v4.6.0, which breaks our lint task. This is a known issue that was fixed in Timber v4.7.0, see more details here:
https://github.com/JakeWharton/timber/issues/292

The impact to us: Our lint report is incomplete because it fails on `IncompatibleClassChangeError` early on, hiding any other lint issues.

This is not urgent since we mitigated the issue by explicitly pulling down Timber 4.7.0. However, it'd be nice to remove this explicit dependency eventually.

Cheers,
Brian

**Comment by arun251** [comment]
Hi @brian98point6, this is fixed in version 2.4.0.
