### ISSUE TITLE
FeatureFlagChange listener is not trigger for Custom Groups

### ISSUE THREAD

**Issue by ShreyashPromact** [launchdarkly/android-client#45]
I need to create a new issue because I am not having an update on my current issue and it is getting closed without having a solution to it.

Please refer [FeatureFlagChange listener is not trigger for Custom Groups](https://github.com/launchdarkly/android-client/issues/43)

It seems like, LaunchDarkly Team just close the issues without having resolution on it. I would be expecting the solution to the issue and not just close the raise issues.

Thanks.

**Comment by arun251** [comment]
Hi @ShreyashPromact,
As I mentioned in #43, we have been communicating with you via the support channel, and that's a better channel for us to respond to you with the particulars of your environment. I'm closing this issue as there isn't a bug with the SDK, but we will continue to help you out through the support channel.

Thanks,
Arun

**Comment by ShreyashPromact** [comment]
@arun251 Ok Fine. But at-least please remain that as open until the issue gets resolved.
Thanks.
