### ISSUE TITLE
Bad slf4j dependency in noveogroup

### ISSUE THREAD

**Issue by manangatangy** [launchdarkly/android-client#46]
Hello Arun,

launchdarkly-android-client:2.4.0 depends on noveogroup-android-logger and
noveogroup-android-logger:1.3.5 explicity packages org.slf4j.impl but only classes:  {AndroidLoggerAdapter,AndroidLoggerFactory,StaticLoggerBinder}.

However this is an old or modified version of org.slf4j.impl -- it's not possible to tell which because there is no version data.

We currently use org.slf4j-simple, which holds org.slf4j.* classes:  {SimpleLogger,SimpleLoggerFactory,StaticLoggerBinder}

The problem is that gradle will pull in two copies of StaticLoggerBinder; one from noveogroup and the other from slf4j-simple.

A better approach is for noveogroup package to NOT include an unversioned and incomplete copy of org.slf4j.impl, but to refer to it as a dependency, which can be managed by gradle, the same as other third-party dependencies.   If launch-darkly cannot change the noveogroup package, then an alternative is for launch-darkly to stop using noveogroup and use alternate logging (perhaps Timber?)

![screen shot 2018-06-05 at 1 43 41 pm](https://user-images.githubusercontent.com/5906257/40955093-3cf9bd84-68cb-11e8-8e9a-10ade09825b1.png)

**Comment by arun251** [comment]
We've fixed this issue in release 2.4.1. Thanks for letting us know and providing great detail.
