### ISSUE TITLE
Can't modify custom attribute of existing LDUser

### ISSUE THREAD

**Issue by mateuszkwiecinski** [launchdarkly/android-client#49]
Since release #36 it is forbidden to change custom attirbutes of existing LDUser.
If you create user by regular:
```
val user = LDUser.Builder("1")
.email("mail@example.com")
.custom("k1","v1")
.custom("k2","v2")
.build()
```
and than you want to modify by using
```
val builder = LDUser.Builder(user)
``` 
you can call `builder.email("newMail@example.com")` but you can't use `builder.custom("k1", "otherValue")` - `UnsupportedOperationException` is thrown due to [Collections.unmodifiableMap](https://github.com/launchdarkly/android-client/blame/master/launchdarkly-android-client/src/main/java/com/launchdarkly/android/LDUser.java#L113).

It is expected behavior? 

I wanted to upgrade library from version 2.1.0 to 2.5.0, but I couldn't find any information what caused this change and how should I migrate to new API.

**Comment by arun251** [comment]
@mateuszkwiecinski This issue has been fixed in release 2.5.1.
