### ISSUE TITLE
Is there a way to reinitialize the LDClient or change mobile keys?

### ISSUE THREAD

**Issue by JacobMuchow** [launchdarkly/android-client#53]
Hey there,

I am working for a company using LaunchDarkly in some existing products and we are creating an Android app. In debug and "beta" builds (distributed to QA testers internally), we provide users the ability to select a specific server (staging, demo, production, etc). from a drop down on the login screen. Each server has a different LD mobile key associated with it.

I have been trying to figure out how to update the LDClient to react to this since it is possible to log in on one server (and initialize LD with that mobile key), logout, then log in a different server (and hopefully reinit LD with this server's mobile key).

At first, I thought I might be able to just call `LDClient.init()` again, but it is set up to only be called once as you know. I was hoping there might be some alternative, like de-initing the client so I can re-init or being able to update the config/mobileKey like you can do with the LDUser.

If this is currently not possible, I'm willing to help out with making the change! We would really love to have this capability so we can continue supporting this flexibility for testing our app.

Thanks

**Comment by arun251** [comment]
Hi @JacobMuchow, there isn't currently a method to do so. You're invited to develop this capability. Thanks!

**Comment by molnarr2** [comment]
@arun251 I've got this implemented and would like to push a PR up for review. Please grant access.

**Comment by torchhound** [comment]
@JacobMuchow we just released a new version of our Android client that has support for multiple LaunchDarkly environments!
