### ISSUE TITLE
Failed to parse date header

### ISSUE THREAD

**Issue by radimjanda754** [launchdarkly/android-client#54]
There is a problem at https://github.com/launchdarkly/android-client/blob/master/launchdarkly-android-client/src/main/java/com/launchdarkly/android/EventProcessor.java

This kind of parsing: `SimpleDateFormat sdf = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss zzz");`
doesnt work, when user's device runs other than US locale. Im trying it with czech and getting `Failed to parse date header` error every time.

However, I think it could work this way `SimpleDateFormat sdf = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss zzz", Locale.US);`

**Comment by arun251** [comment]
Thanks for that, @radimjanda754 . That should be an easy fix.

**Comment by arun251** [comment]
This issue is resolved in release 2.5.2.
