### ISSUE TITLE
Auth header parsing issue

### ISSUE THREAD

**Issue by austinfinnql** [launchdarkly/android-client#56]
Hi guys,

While testing something that uses a LaunchDarkly flag, I noticed there is an Auth header parsing error occurring with the Android SDK. The issue doesn't seem to happen with the iOS SDK. The place I work at has 2 different apps that use LD and both have the same parsing issue. One app uses version 2.1.2 and the other uses 2.3.2. I had a look at the "CHANGELOG.md" but couldn't find any fix that related to this issue. I was able to resolve the issue with Charles Proxy by prefixed "api_key" to the auth token/header and it fixed the parsing issue.

FYI, I still get 200 responses even with this parsing issue. I would have thought that all the calls should fail if the auth header/token can't be parsed.

**Comment by arun251** [comment]
Hi @austinfinnql,

This is strange -- we've never seen that before. Can you share the error you're receiving (with a full stack trace, if there is one)? Feel free to send a note to support@launchdarkly.com if you need to share sensitive information.

**Comment by arun251** [comment]
What you're seeing seems to be a parsing issue with Charles Proxy and not an issue that affects LaunchDarkly SDK functionality. However, I suspect the root cause is that the Android SDK isn't quite compliant with the HTTP RFC regarding the Authorization header. We can fix this by adding the `api_key` scheme to the request header.

**Comment by austinfinnql** [comment]
Grand. Thanks for looking into it.

**Comment by arun251** [comment]
Hi @austinfinnql we've made a change in release 2.5.4 to work around the issue you were seeing with Charles.
