### ISSUE TITLE
Can't init the LDClient that return  Future<LDClient> in background thread

### ISSUE THREAD

**Issue by jazzyjester** [launchdarkly/android-client#65]
Hello, 
Thanks for a great library and service.

I notice an issue related to initialization the launch darkly when using the `init` method that return `Future<LDClient>`

When I run this init inside background thread, I receive this error : 

01-28 11:31:01.939 Can't create handler inside thread that has not called Looper.prepare()
01-28 11:31:01.939 init failed
    java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:200)
        at android.os.Handler.<init>(Handler.java:114)
        at com.launchdarkly.android.Throttler.<init>(Throttler.java:39)
        at com.launchdarkly.android.LDClient.<init>(LDClient.java:223)
        at com.launchdarkly.android.LDClient.init(LDClient.java:102)

When I run it inside UI thread, it works.
Can you please check why I can't run it inside background thread ?
Thanks.
Ronny.

**Comment by gwhelanLD** [comment]
Hi Ronny,

Thank you for the report, we'll take a look into this issue and update you when we know more.

Thanks,
Gavin Whelan
SDK Team

**Comment by jazzyjester** [comment]
@arun251 I was using 2.5.2, without the fix, Checked with 2.5.3 version and it was fixed !
Thank you !

**Comment by gwhelanLD** [comment]
@jazzyjester Thanks for checking your version and confirming the fix, closing as resolved in 2.5.3+.
