### ISSUE TITLE
[Readme] Is proguard-config section up-to-date?

### ISSUE THREAD

**Issue by mateuszkwiecinski** [launchdarkly/android-client#68]
**Describe the bug**
I started wondering if current version of [Proguard-config](https://github.com/launchdarkly/android-client#proguard-config) is still valid.
Is there really a requirement to add those lines to app's proguard file? 

As far as I can see the library publishes proper proguard rules using [consumer-proguard mechanism](https://github.com/launchdarkly/android-client/blob/master/launchdarkly-android-client/build.gradle#L31)

If adding those lines is still a valid requirement, can I ask to add missing rules to published file to make library integration more straightforward?

**Comment by gwhelanLD** [comment]
Hi mateuszkwiecinski, thanks for reaching out.

I do believe those proguard config options should probably be unnecessary at this point. They also do seem to be slightly out of date compared to the `consumer-proguard-rules.pro` file. I'll go ahead and modify the readme to remove the proguard config lines, but leave the section with a note linking to the `consumer-proguard-rules.pro` file in case there are build setups out there which would require setting the proguard rules manually. 

Would that resolve this issue for you?

Thanks for the question/suggestion!

**Comment by gwhelanLD** [comment]
Here's my proposed changes:
https://github.com/launchdarkly/android-client/blob/gw/readme-proguard-config/README.md

Let me know if this solves your question, if so I'll get it reviewed and merged in.

Thanks

**Comment by mateuszkwiecinski** [comment]
> Let me know if this solves your question,

Completely! Thanks for that quick reply! 

Additionaly If I may suggest something - you may want to mention R8 somewhere in the doc. R8 became default shrinking tool in AGP 3.4.0, so instead of writing just _"ProGuard Config"_ I'm suggesting to write _"Proguard/R8 Config"_ and _"If you're using ProGuard"_ -> _"If you're using ProGuard or R8"_ and so on.

**Comment by gwhelanLD** [comment]
Great suggestion, I've incorporated it and created a pull request. I'll go ahead and close this issue once that gets merged.

Thanks again.
